name: Run source code linter
description: Run a linting tool on repository folders
inputs:
  cmd:
    description: Linting command
    required: true
  diff-cmd:
    description: Command to generate diff on failure
    default: ""
  diff-language:
    description: Specify the language when showing the formatting errors
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install linting tools
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run linter
      shell: bash
      run: ${{ inputs.cmd }}

    - name: Print formatting errors
      if: ${{ failure() &&  inputs.diff-cmd != "" }}
      shell: bash
      run: |
        out=$(${{ inputs.diff-cmd }})

        echo "${out}"
        echo "\`\`\`${{ inputs.diff-language }}" >> $GITHUB_STEP_SUMMARY
        echo "${out}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
