name: PR Lint, Build, and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/run-linter
        with:
          cmd: python ./scripts/run-clang-format
          sources: include src
          check-args: --check
          diff-args: --diff
          diff-lang: cpp

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/run-linter
        with:
          cmd: black
          sources: conanfile.py scripts/run-mypy scripts/run-clang-format
          check-args: --check
          diff-args: --diff
          diff-lang: python

  build-cpp:
    runs-on: ubuntu-latest
    needs: lint-cpp
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build dependencies
        id: install-deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          wget https://apt.llvm.org/llvm.sh
          chmod u+x ./llvm.sh
          sudo ./llvm.sh 19
          echo "CONAN_CONFIG_HOME=$(conan config home)" >> "$GITHUB_OUTPUT"

      - name: Restore Conan build cache
        id: conan-restore-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.install-deps.outputs.CONAN_CONFIG_HOME }}
          key: ${{ runner.os }}-conan-cache

      - name: Install app dependencies
        run: |
          conan install . -pr:a ./profiles/linux-x86_64 --build=missing

      - name: Save Conan build cache
        id: conan-save-cache
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.install-deps.outputs.CONAN_CONFIG_HOME }}
          key: ${{ steps.conan-restore-cache.outputs.cache-primary-key }}

      - name: Build project
        run: |
          cmake --preset conan-release
          cmake --build --preset conan-release

      - name: Run project tests
        run: |
          cd build/Release
          ctest
        timeout-minutes: 5
