name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build dependencies
        id: install-deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements-docs.txt
          wget https://apt.llvm.org/llvm.sh
          chmod u+x ./llvm.sh
          sudo ./llvm.sh 19
          sudo apt install doxygen
          echo "CONAN_CONFIG_HOME=$(conan config home)" >> "$GITHUB_OUTPUT"

      - name: Restore Conan build cache
        id: conan-restore-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.install-deps.outputs.CONAN_CONFIG_HOME }}
          key: ${{ runner.os }}-conan-cache

      - name: Install app dependencies
        run: |
          conan install . -pr:a ./profiles/linux-x86_64 --build=missing -o "&:build_docs=True"

      - name: Build documentation
        run: |
          cmake --preset conan-release
          cd build/Release
          make docs

      - name: Package documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/Release/docs/sphinx/

  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.package.output.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
