name: Run Linters

on: [pull_request]

jobs:
  lint-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/run-linter
        with:
          cmd: python ./scripts/run-clang-format lint include src
          diff-cmd: python ./scripts/run-clang-format lint include src
          diff-language: cpp

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/run-linter
        with:
          cmd: black --check scripts
          diff-cmd: black --diff scripts
          diff-language: python
