name: Run Linters

on: [pull_request]

jobs:
  lint-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/run-linter
        with:
          cmd: python ./scripts/run-clang-format
          sources: include src
          check-args: --check
          diff-args: --diff
          diff-lang: cpp

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/run-linter
        with:
          cmd: black
          sources: scripts/run-mypy scripts/run-clang-format
          check-args: --check
          diff-args: --diff
          diff-lang: python
